// src/components/Entry.vue
<template>
  <!-- New Entry -->
  <textarea
    v-model="entry.text"
    class="newEntry entry"
    :class="[entry.color, { checked: entry.active }]"
    v-if="entry.new"
    ref="newEntry"
    v-on:blur="createEntry(entry)"
    v-on:keydown.enter="$event.target.blur()"
  >
  </textarea>
  <!-- End New Entry -->

  <!-- Inactive Entry (fade-in  was added previously but it looked a little funny) -->
  <li
    v-else-if="mode === ''"
    class="entry"
    :class="[entry.color, { checked: entry.active }]"
    @click="changeMode('menu')"
  >
    {{ entry.text }}
  </li>
  <!-- End Inactive Entry -->

  <!-- Its the fact that it's getting rerendered -->
  <!-- Active -->
  <li
    v-else
    class="entry"
    :class="[entry.color]"
    @click="(e) => altChangeActive(e)"
  >
    <div class="entry-container">
      <p class="text" v-if="mode !== 'edit'" :class="{ checked: entry.active }">
        {{ entry.text }}
      </p>

      <!-- Begin Edit Entry TextArea -->
      <textarea
        v-model="newText"
        :class="textClass"
        ref="textarea"
        class="editEntry"
      ></textarea>
      <!-- Begin Edit Entry TextArea -->

      <!-- Button Container -->
      <div class="button-container">
        <!-- Color -->
        <button
          @click="changeMode('color')"
          :disabled="mode === 'color'"
          class="entryBtn"
        >
          <img
            :style="{ filter: 'invert(1)' }"
            alt="color"
            src="/assets/entry_icons/palette.png"
          />
          <select :value="''" @input="selectColor($event.target.value)">
            <option
              v-for="(option, index) in colorOptions"
              :value="option"
              :key="index"
              :class="option"
            >
              {{ option }}
            </option>
          </select>
        </button>

        <!-- Begin Time -->
        <!-- Superimpose time and input on top of each other -->
        <div id="time-section">
          <img
            :style="{ filter: 'invert(1)' }"
            alt="clock"
            src="/assets/entry_icons/clock.png"
          />
          <input
            class="entryBtn"
            v-model="time"
            @mouseup="changeTimeMode"
            @input="selectTime"
            placeholder="none"
            ref="time"
            type="time"
          />
        </div>

        <!-- End Time -->

        <!-- Save Edit -->
        <button v-if="mode === 'edit'" @click="submitEdit" class="entryBtn">
          <img
            :style="{ filter: 'invert(1)' }"
            alt="save"
            src="/assets/entry_icons/save.png"
          />
        </button>
        <!-- Begin Edit -->
        <button v-if="mode !== 'edit'" @click="editEntry" class="entryBtn">
          <img
            :style="{ filter: 'invert(1)' }"
            alt="edit"
            src="/assets/entry_icons/edit.png"
          />
        </button>

        <!-- Check Entry -->
        <button @click="checkEntry" class="entryBtn">
          <img
            :style="{ filter: 'invert(1)' }"
            alt="done"
            src="/assets/entry_icons/done.png"
          />
        </button>
        <!-- Delete Entry -->
        <button @click="() => deleteEntry(entry.key)" class="entryBtn">
          <img
            :style="{ filter: 'invert(1)' }"
            alt="delete"
            src="/assets/entry_icons/delete.png"
          />
        </button>
      </div>
      <!-- End Button Container -->
    </div>
  </li>
  <!-- End Active Entry -->
</template>
<script>
import { actions } from "../utils";
export default {
  props: {
    deleteEntry: {
      required: true,
      type: Function,
    },
    dragStart: {
      required: false,
      type: Function,
    },
    entry: {
      required: true,
      type: Object,
    },
    listDate: {
      type: Date,
    },
    createEntry: {
      type: Function,
      required: true,
    },
    updateEntry: {
      type: Function,
      required: true,
    },
  },
  data() {
    return {
      time: "",
      newText: "",
      mode: "",
    };
  },
  created() {
    this.time = this.entry.time || "";
  },
  mounted() {
    if (this.$refs.newEntry) this.$refs.newEntry.focus(); // add focus on new entry textarea
  },
  methods: {
    altChangeActive(e) {
      if (
        e.target.classList.contains("text") ||
        e.target.classList.contains("entry") ||
        e.target.classList.contains("entry-container") ||
        e.target.classList.contains("entryBtnContainer")
      ) {
        this.changeMode("");
      }
    },
    changeTimeMode() {
      if (this.mode !== "time") {
        this.changeMode("time");
      } else {
        this.$refs.time.style.display = "none";
        this.changeMode("menu");
        setTimeout(() => (this.$refs.time.style.display = "block"), 1);
      }
    },
    changeMode(type) {
      this.mode = type;
    },
    selectColor(color) {
      if (color !== this.entry.color) {
        this.entry.color = color;
        this.changeMode("menu");
        this.updateEntry(this.entry.key);
      }
    },
    selectTime() {
      console.debug("selectTime");
      if (!this.entry.time) {
        let eventDate = new Date(this.listDate);
        let hours = parseInt(this.time[0] + this.time[1]);
        let minutes = parseInt(this.time[3] + this.time[4]);
        eventDate.setSeconds(0);
        eventDate.setHours(hours);
        eventDate.setMinutes(minutes);
        const ms = eventDate.getTime() - Date.now();
        if (ms > 0) {
          actions.createNotification({
            name: this.entry.key,
            time: eventDate.getTime(),
          });
        }
      }

    },
    submitTime() {
      this.changeMode("menu");
    },
    checkEntry() {
      this.entry.active = !this.entry.active;
      this.updateEntry(this.entry.key);
    },
    editEntry() {
      this.mode = "edit";
      this.$refs.textarea.focus();
      this.newText = this.entry.text;
    },
    submitEdit() {
      this.mode = "";
      if (this.newText !== this.entry.text) {
        this.entry.text = this.newText;
        this.newText = "";
        this.updateEntry(this.entry.key);
      }
    },
  },

  computed: {
    textClass: {
      get() {
        return this.mode === "edit" ? "show" : "no-show";
      },
    },
    colorOptions: {
      get() {
        return ["blue", "green", "gold", "purple", "orange", "red"];
      },
    },
  },
};
</script>

<style scoped lang="scss">
$brightness: 100%;

// Modify semantic tags here
textarea {
  font-family: "Segoe UI", Tahoma, sans-serif;
  resize: none;
  &::-webkit-scrollbar {
    width: 10px;
  }
  &::-webkit-scrollbar-thumb {
    width: 10px;
    border: 4px solid rgba(0, 0, 0, 0);
    background-clip: padding-box;
    background-color: #fff;
    transition: background 0.5s;
    box-shadow: inset -1px -1px 0px rgb(0 0 0 / 5%),
      inset 1px 1px 0px rgb(0 0 0 / 5%);
    border-radius: 25px;
  }
  &::-webkit-scrollbar-button {
    width: 0;
    height: 0;
    display: none;
  }
}

input[type="time"] {
  display: block;
  position: absolute;
  padding-inline-start: 0px;
  border: none;
  background: none;
  color: white;
  width: 25px;
  height: 25px;
  transform: translateY(-28px);

  // clock
  &::-webkit-calendar-picker-indicator {
    display: flex;
    cursor: pointer;
    width: 25px;
    height: 25px;
    background: none;
    padding: 0px;
    margin: 0px;
  }

  /* Wrapper around the hour, minute, second, and am/pm fields as well as 
the up and down buttons and the 'X' button */
  &::-webkit-datetime-edit-fields-wrapper {
    // display: flex;
    display: none;
  }
  /* The space between the fields - between hour and minute, the minute and 
second, second and am/pm */
  &::-webkit-datetime-edit-text {
    display: none;
    // padding: 19px 4px;
  }

  /* The naming convention for the hour, minute, second, and am/pm field is
`-webkit-datetime-edit-{field}-field` */

  /* Hour */
  &::-webkit-datetime-edit-hour-field {
    background: rgb(56 147 200 / 75%);
    border-radius: 15%;
    color: #fff;
  }

  /* Minute */
  &::-webkit-datetime-edit-minute-field {
    background: rgb(56 147 200 / 75%);
    border-radius: 15%;
    color: #fff;
  }

  /* AM/PM */
  &::-webkit-datetime-edit-ampm-field {
    background: rgb(56 147 200 / 75%);
    border-radius: 15%;
    display: none;
    color: #fff;
  }

  /* 'X' button for resetting/clearing time */
  &::-webkit-clear-button {
    display: none;
  }

  /* Up/Down arrows for incrementing/decrementing the value */
  &::-webkit-inner-spin-button {
    display: none;
  }
}

select {
  color: transparent;
  -webkit-appearance: none;
  -moz-appearance: none;
  text-indent: 1px;
  text-overflow: "";
  height: 25px;
  position: absolute;
  background: none;
  border: none;
  outline: none;
  // width:100%;
  width: 25px;
  transform: translateX(-23px);
}

select option {
  margin: 40px;
  background: rgba(0, 0, 0, 0.3);
  color: #fff;
  text-shadow: 0 1px 0 rgba(0, 0, 0, 0.4);
}

.checked {
  text-decoration: line-through;
}

.entry {
  width: 90%;
  text-align: center;
  white-space: normal;
  display: block;
  overflow: hidden;
  text-overflow: ellipsis;
  border: none;
  touch-action: none;
  user-select: none;
  transition: background 0.5s;
  color: white;
  margin: 0.25rem auto;
  padding: 0.5rem;
  border-radius: 25px;
  font-size: 0.9rem;
  &:hover {
    cursor: pointer;
  }
  .entry-container {
    display: flex;
    flex-direction: column;
    justify-content: center;
    .editEntry {
      font-family: "Segoe UI", Tahoma, sans-serif !important;
      border: none;
      padding: 0;
      margin-block-start: 1em;
      margin-block-end: 1em;
      float: left;
      background: none;
      color: white;
      text-overflow: ellipsis;
      height: 60px;
      &.show {
        opacity: 1;
      }
      &.no-show {
        margin: 0 auto;
        opacity: 0;
        height: 0;
      }
    }
  }
}

.newEntry {
  transition: none;
  margin: 0.25rem auto;
  float: left;

  animation-name: "grow";
  animation-fill-mode: forwards;
  animation-duration: 0.25s;

  &:focus {
    border: none;
    outline: none;
  }
}

.entryBtn {
  background: none;
  transition: background 0.5s;
  padding: 0;
  width: 25px;
  height: 25px;
  font-size: 0.9rem;
  border-radius: 100%;
  &:hover {
    // background: #00000073;
    background: #2a2a2a73;
    filter: brightness($brightness);
  }
}

.activeBtn {
  color: rgb(0 0 0 / 0.69);
}

.button-container {
  display: flex;
  justify-content: space-evenly;
}

@keyframes grow {
  from {
    width: 10%;
  }
  to {
    width: 90%;
  }
}

.fade-in {
  animation-name: "fadeIn";
  animation-fill-mode: forwards;
  animation-duration: 0.25s;
}

@keyframes fadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 0.75;
  }
}

// COLORS
.blue {
  background: rgba(21, 115, 170, 0.75);
}

.green {
  background: rgba(7, 128, 7, 0.75);
}

.gold {
  background: rgba(185, 174, 8, 0.75);
}

.purple {
  background: rgba(122, 39, 138, 0.75);
}

.orange {
  background: rgba(251, 119, 5, 0.75);
}

.red {
  background: rgba(220, 5, 5, 0.75);
}

.cyan {
  background: rgba(0, 220, 255, 0.75);
}
</style>

// src/components/Entry/Entry.jsx
import { useEffect, useRef, useState } from 'preact/hooks';
import { actions } from '../../utils/index';
import styles from './Entry.module.scss';

const entryModes = {
  NEW: 'NEW',
  INACTIVE: 'INACTIVE',
  ACTIVE: 'ACTIVE',
  EDIT: 'EDIT',
  COLOR: 'COLOR',
  SELECTEDCOLOR: 'SELECTEDCOLOR',
  TIME: 'TIME',
};
const colorOptions = ['blue', 'green', 'gold', 'purple', 'orange', 'red'];
function Entry({
  entry,
  entryDragStart,
  entryDragEnd,
  dateStamp,
  createEntry,
  updateEntry,
  deleteEntry,
}) {
  const [time, setTime] = useState(entry.time || '');
  const [mode, setMode] = useState(entryModes.INACTIVE);
  const [newText, setNewText] = useState(entry.text);
  const [newColor, setNewColor] = useState(entry.color);
  const editRef = useRef(null);
  const newRef = useRef(null);
  const timeRef = useRef(null);

  const changeMode = (event, newMode) => {
    event.stopPropagation();
    setMode(newMode);
  };

  const toggleCompleted = (event) => {
    console.log('toggle completed');
    updateEntry(entry.key, { active: !entry.active });
    event.stopPropagation();
  };

  const selectColor = (selectedColor) => {
    console.log('submit color');
    console.log({ selectedColor });
    if (selectedColor === entry.color) return;
    setNewColor(selectedColor);
    updateEntry(entry.key, { color: selectedColor });
  };

  const submitEdit = () => {
    console.log('submit edit');
    const updatedEntry = {
      ...entry,
      text: newText,
    };
    updateEntry(entry.key, { text: newText });
  };

  // You must actually submit time in order to create a notification
  const submitTime = () => {
    timeRef.current.style.display = 'none';
    setTimeout(() => (timeRef.current.style.display = 'block'), 1);
    if (entry.time === time) return;
    const entryDate = new Date(dateStamp.replace(/_/g, '/'));
    const hours = parseInt(time[0] + time[1]);
    const minutes = parseInt(time[3] + time[4]);
    entryDate.setSeconds(0);
    entryDate.setHours(hours);
    entryDate.setMinutes(minutes);
    const ms = entryDate.getTime() - Date.now();
    if (ms > 0) {
      actions.createNotification({
        name: entry.key,
        time: entryDate.getTime(),
      });
    }
    updateEntry(entry.key, { time });
  };

  useEffect(() => {
    if (entry.new && mode !== entryModes.NEW) {
      setMode(entryModes.NEW);
    }
  }, []);
  useEffect(() => {
    console.log({ mode });
    if (mode === entryModes.NEW) {
      newRef.current.focus();
    }
    if (mode === entryModes.EDIT) {
      editRef.current.focus();
    }
  }, [mode]);

  if (mode === entryModes.NEW) {
    return (
      <textarea
        ref={newRef}
        value={newText}
        onChange={(e) => {
          console.log('value changed');
          const text = e.target.value;
          if (text.length === 0) return deleteEntry(entry.key);
          // delete new property
          delete entry.new;
          const newEntry = {
            ...entry,
            text,
          };
          setNewText(e.target.value);
          createEntry(newEntry);
          setMode(entryModes.INACTIVE);
        }}
        className={`${styles.newEntry} ${styles.entry} ${styles[entry.color]}`}
        // onBlur={() => {}}
        onKeyDown={(e) => {
          if (e.key === 'Enter') {
            console.log('blur target');
            e.target.blur();
          }
        }}
        //   :class="[entry.color, { checked: entry.active }]"
      ></textarea>
    );
  }

  if (mode === entryModes.INACTIVE) {
    return (
      <li
        className={`${styles.entry} ${styles[entry.color]}  ${
          entry.active ? styles.checked : ''
        }`}
        onClick={() => setMode(entryModes.ACTIVE)}
        draggable={true}
        onDragStart={(e) => {
          const draggedEntry = {
            ...entry,
            text: newText,
          };
          entryDragStart(e, draggedEntry, dateStamp);
        }}
        onDragEnd={(e) => {
          entryDragEnd(e, entry.key);
        }}
        //   :class="[entry.color, { checked: entry.active }]"
      >
        {newText}
      </li>
    );
  }

  //   Menu Mode
  return (
    <li
      className={`${styles.entry} ${styles[newColor]}`}
      draggable={true}
      onDragStart={(e) => {
        const draggedEntry = {
          ...entry,
          text: newText,
        };
        entryDragStart(e, draggedEntry, dateStamp);
      }}
      onDragEnd={(e) => {
        entryDragEnd(e, entry.key);
      }}
      onClick={(e) => {
        if (mode === entryModes.ACTIVE) {
          changeMode(e, entryModes.INACTIVE);
        }
      }}
    >
      <div className={styles.entry_container}>
        {mode === entryModes.EDIT ? (
          <textarea
            ref={editRef}
            className={`${styles.editEntry} ${
              entryModes.EDIT ? styles.show : styles.no_show
            }`}
            onChange={(e) => {
              console.log('value changed');
              const text = e.target.value;
              if (text.length === 0) return deleteEntry(entry.key);
              if (text === entry.text) return;
              setNewText(e.target.value);
            }}
            value={newText}
          ></textarea>
        ) : (
          <p className={`${entry.active ? styles.checked : ''}`}>{newText}</p>
        )}

        <div class={styles.button_container}>
          <button
            onClick={(e) => {
              console.log('button was clicked');
              console.log({ clickColorMode: mode });
              if (mode !== entryModes.SELECTEDCOLOR) {
                changeMode(e, entryModes.COLOR);
              } else {
                changeMode(e, entryModes.ACTIVE);
              }
            }}
            disabled={mode === entryModes.COLOR}
            className={styles.entryBtn}
          >
            <img
              style={{ filter: 'invert(1)' }}
              alt="color"
              src="/assets/entry_icons/palette.png"
            />
            <select
              value={entry.color}
              onInput={(e) => {
                selectColor(e.target.value);
                changeMode(e, entryModes.SELECTEDCOLOR);
              }}
            >
              {colorOptions.map((color) => (
                <option value={color} className={styles[entry.color]}>
                  {color}
                </option>
              ))}
            </select>
          </button>

          {/* <!-- Superimpose time and input on top of each other --> */}
          <div id="time-section">
            <img
              style={{ filter: 'invert(1)' }}
              alt="clock"
              src="/assets/entry_icons/clock.png"
            />
            <input
              className={styles.entryBtn}
              onBlur={(event) => {
                changeMode(event, entryModes.ACTIVE);
              }}
              onClick={(e) => {
                if (mode !== entryModes.TIME) {
                  return changeMode(e, entryModes.TIME);
                }
                submitTime();
              }}
              value={time}
              onInput={(e) => setTime(e.target.value)}
              placeholder="none"
              ref={timeRef}
              type="time"
            />
          </div>

          {mode === entryModes.EDIT ? (
            <button
              onClick={(e) => {
                changeMode(e, entryModes.ACTIVE);
                submitEdit();
              }}
              className={styles.entryBtn}
            >
              <img
                style={{ filter: 'invert(1)' }}
                alt="save"
                src="/assets/entry_icons/save.png"
              />
            </button>
          ) : (
            <button
              onClick={(e) => {
                changeMode(e, entryModes.EDIT);
              }}
              className={styles.entryBtn}
            >
              <img
                style={{ filter: 'invert(1)' }}
                alt="edit"
                src="/assets/entry_icons/edit.png"
              />
            </button>
          )}

          {/* <!-- Check Entry --> */}
          <button onClick={toggleCompleted} className={styles.entryBtn}>
            <img
              style={{ filter: 'invert(1)' }}
              alt="done"
              src="/assets/entry_icons/done.png"
            />
          </button>
          {/* <!-- Delete Entry --> */}
          <button onClick={() => deleteEntry(entry.key)} className={styles.entryBtn}>
            <img
              style={{ filter: 'invert(1)' }}
              alt="delete"
              src="/assets/entry_icons/delete.png"
            />
          </button>
        </div>
      </div>
    </li>
  );
}

export default Entry;
