// src/components/Toggle/Toggle.jsx

import styles from './styles.module.scss'

function Toggle({ description, toggleItem, name, currentValue }) {
    return (
        <div>
            {description}
            <label
                onClick={(e) => toggleItem(e, name)}
                //  @click="() => toggleItem($event, name)" 
                for="switch" className={styles.switch}>
                <input type="checkbox" className={styles.toggle}
                // :checked="currentValue" 
                />
                <span className={`${styles.slider} ${styles.round}`}></span>
            </label>
        </div>
    )
}

export default Toggle;

// src/js/popup/components/Toggle.vue
<template>
  <div>
    {{ description }}
    <label @click="toggleItem($event, name)" for="switch" class="switch">
      <input type="checkbox" class="toggle" v-model="currentValue" />
      <span class="slider round"></span>
    </label>
  </div>
</template>

<script>
export default {
  props: {
    description: {
      type: String,
      required: true,
    },
    name: {
      type: String,
      required: true,
    },
    toggleItem: {
      type: Function,
      required: true,
    },
    currentValue: {
      type: Boolean,
      required: false,
    },
  },

  watch: {
    currentValue(val) {},
  },
};
</script>
