// src/js/app/components/Week.vue
<template>
  <div id="week">
    <div class="nav">
      <button @click="changeDate(-7)" class="arrow">←</button>
      <div
        class="title"
        style="
          width: 22rem;
          background: rgba(5, 80, 123, 0.992);
          border-radius: 75px;
        "
      >
        {{ weekRange }}
      </div>
      <button @click="changeDate(7)" class="arrow">→</button>
    </div>
    <div class="weekdayNames">
      <h2>Sunday</h2>
      <h2>Monday</h2>
      <h2>Tuesday</h2>
      <h2>Wednesday</h2>
      <h2>Thursday</h2>
      <h2>Friday</h2>
      <h2>Saturday</h2>
    </div>
    <div class="weekdays">
      <EntryList
        v-for="(date, index) in dateList"
        :key="index"
        :listDate="date"
        :dateTitle="true"
        :classNames="['weekday']"
      />
    </div> 
  </div>
</template>


<script>
import EntryList from "./EntryList";
export default {
  components: {
    EntryList,
  },
  data() {
    return {
      date: new Date(),
    };
  },
  created() {},
  methods: {
    changeDate(amount) {
      let changeDate = new Date(this.date); // had to do this because computed couldn't see that it was updating
      changeDate.setDate(this.date.getDate() + amount);
      this.date = changeDate;
    },
  },
  computed: {
    weekRange() {
      let startDate = new Date(this.date);
      while (startDate.getDay() !== 0)
        startDate.setDate(startDate.getDate() - 1);
      let endDate = new Date(startDate);
      endDate.setDate(endDate.getDate() + 6);
      return `${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}`;
    },
    dateList() {
      let dates = [];
      let startDate = new Date(this.date);
      while (startDate.getDay() !== 0) {
        startDate.setDate(startDate.getDate() - 1);
      }
      for (let i = 0; i < 7; i++) {
        let thisDate = new Date(startDate); // create a new date so as not to reference the main one we are copying
        dates.push(thisDate);
        startDate.setDate(startDate.getDate() + 1);
      }
      return dates;
    },
  },
};
</script>

<style lang="scss" scoped>
.weekdayNames {
  h2 {
    padding: 0px 0px 0.5rem;
    text-align: center;
  }
}
</style>

// src/components/Week/Week.jsx
import { useState, useEffect } from 'preact/hooks';
import EntryList from '../EntryList/EntryList';
import styles from './Week.module.scss';

function Week() {
  const [date, setDate] = useState(new Date());
  const [weekdays, setWeekdays] = useState([]);
  const [weekTitle, setWeekTitle] = useState('');

  const changeDay = (amount) => {
    const newDate = new Date(date);
    newDate.setDate(newDate.getDate() + amount);
    setDate(newDate);
  };

  const getDates = () => {
    const dates = [];
    const startDate = new Date(date);
    while (startDate.getDay() !== 0) {
      startDate.setDate(startDate.getDate() - 1);
    }
    for (let i = 0; i < 7; i++) {
      const thisDate = new Date(startDate); // create a new date so as not to reference the main one we are copying
      dates.push(thisDate);
      startDate.setDate(startDate.getDate() + 1);
    }
    const newWeekdays = dates.map((newDate) =>
      newDate.toLocaleDateString(undefined, { weekday: 'long' })
    );
    setWeekdays(newWeekdays);
  };

  const getWeekTitle = () => {
    const startDate = new Date(date);
    while (startDate.getDay() !== 0) startDate.setDate(startDate.getDate() - 1);
    const endDate = new Date(startDate);
    endDate.setDate(endDate.getDate() + 6);
    setWeekTitle(`${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}`);
  };

  useEffect(() => {
    getWeekTitle();
    getDates();
  }, [date]);

  return (
    <div id={styles.week}>
      <div className={styles.nav}>
        <button onClick={() => changeDay(-7)} className="arrow">
          ←
        </button>
        <div
          className="title"
          style="
              width: 22rem;
              background: rgba(5, 80, 123, 0.992);
              border-radius: 75px;
            "
        >
          {weekTitle}
        </div>
        <button onClick={() => changeDay(7)} className="arrow">
          →
        </button>
      </div>
      <div className={styles.weekdayNames}>
        {weekdays.length > 0 ? weekdays.map((weekday) => <h2>{weekday}</h2>) : ''}
      </div>
      <div className={styles.weekdays}>
        {weekdays.length > 0 ? weekdays.map(weekday => (
        <EntryList />

        )) : ''}
        {/* <EntryList
            v-for="(date, index) in dateList"
            :ref="`${index}`"
            :key="index"
            :id="index"
            :listDate="date"
            :dateTitle="true"
            :classNames="['weekday']"
          /> */}
      </div>
    </div>
  );
}

export default Week;
