// extension/src/js/app/components/EntryList/index.vue
<template>
  <div
    class="details"
    :class="addClasses"
    @drop="onDrop($event)"
    @dragover.prevent
    ref="details"
  >
    <div v-if="dateTitle" :style="todayDate" class="dateTitle">
      {{ dayNumber }}
    </div>

    <ul v-if="Object.keys(entries).length" ref="entryList" class="entryList">
      <Entry
        v-for="(entry, key, index) in entries"
        :key="index"
        :entryKey="key"
        :entry="entry"
        :createEntry="createEntry"
        :updateEntry="updateEntry"
        :deleteEntry="deleteEntry"
        :listDate="listDate"
        :dragStart="dragStart"
      />
    </ul>
    <ul v-else ref="entryList" class="entryList"></ul>

    <button @click="initEntry" :value="dateStamp" class="addButton">+</button>
  </div>
</template>

<script>
import Entry from "../Entry.vue";
import { onAuthStateChanged } from "firebase/auth";
import { actions } from "../../utils/store";
import shortid from "shortid";
import Vue from "vue";
// https://stackoverflow.com/questions/18548465/prevent-scroll-bar-from-adding-up-to-the-width-of-page-on-chrome
export default {
  components: {
    Entry,
  },
  // Eventually pass in props for styling component
  props: {
    listDate: {
      type: Date,
      required: true,
    },
    dateTitle: {
      type: Boolean,
      required: false,
    },
    classNames: {
      type: Array,
      required: false,
    },
  },
  data() {
    return {
      entries: {},
      isOver: false,
    };
  },

  created() {
    // Create an event listener for if the alarm of reloadFirestore
    // goes off
    // chrome.storage.onChanged.addListener(this.checkChanges);
    this.readEntries();
    onAuthStateChanged(this.$auth, this.readEntries); // this watches to see if a user logs in or logs off
  },

  watch: {
    // do this if we change the date
    listDate(newValue) {
      this.readEntries();
    },
  },

  mounted() {
    // https://learnvue.co/2020/01/how-to-add-drag-and-drop-to-your-vuejs-project/
    this.$refs.details.addEventListener("dragenter", () => {
      this.isOver = true;
    });
    this.$refs.details.addEventListener("dragleave", () => {
      this.isOver = false;
    });
  },

  methods: {
    initEntry() {
      // console.log("Init Entry");
      // Add to entries state and to chrome storage
      let newEntry = {
        text: "",
        color: "blue",
        active: false,
        new: true,
      };

      // Need to use Vue.set in order to have reactivity for objects
      Vue.set(this.entries, shortid.generate(), newEntry);
    },

    //===============
    // DRAG FUNCTIONS
    //===============
    // https://learnvue.co/2020/01/how-to-add-drag-and-drop-to-your-vuejs-project/
    // Start of drag
    dragStart(evt, key, entry, parentId) {
      // We need a callback so we can remove from the original data and entries list
      evt.dataTransfer.dropEffect = "move";
      evt.dataTransfer.effectAllowed = "move";

      // https://stackoverflow.com/questions/9533585/drag-drop-html-5-jquery-e-datatransfer-setdata-with-json
      evt.dataTransfer.setData("text/plain", JSON.stringify(entry));
      evt.dataTransfer.setData("parentId", parentId);
      evt.dataTransfer.setData("key", key);
    },
    // On drop, we will add to our list and delete from old one
    onDrop(evt) {
      this.isOver = false;
      // get original parent id
      const parentId = parseInt(evt.dataTransfer.getData("parentId"));
      const key = evt.dataTransfer.getData("key");

      // If in the same list, exit the function
      if (parentId === this._uid) return;

      // Else, lets grab the data from datatransfer
      const entryJSON = evt.dataTransfer.getData("text/plain");
      const entry = JSON.parse(entryJSON);

      // find the original parent component by reference of this parent
      let originalParent = this.$parent.$children.filter(
        (list) => list._uid === parentId
      )[0];

      originalParent.deleteEntry(key);
      Vue.set(this.entries, key, entry);
      this.createEntry(entry, key);
    },
    // END DRAG FUNCTIONS

    //===============
    // CRUD FUNCTIONS
    //===============
    createEntry(entry, key) {
      if (entry.text.length === 0) {
        Vue.delete(this.entries, key);
      } else {
        Vue.delete(this.entries[key], "new");
        actions
          .create({ date: this.dateStamp, entry, key })
          .then((result) => {
            // console.log(result);
          })
          .catch((e) => console.error(e));
      }
    },
    readEntries() {
      console.log("read entries");
      actions
        .read({ date: this.dateStamp })
        .then((result) => {
          this.entries = result;
        })
        .catch((e) => console.error(e));
    },

    updateEntry(key) {
      // check if entry is any different than before
      // Instead of doing just this i should specify what is being changed maybe?
      Vue.set(this.entries, key, this.entries[key]);
      actions
        .update({ date: this.dateStamp, entry: this.entries[key], key })
        .then((result) => {
          // console.log(result);
        })
        .catch((e) => console.error(e));
    },

    deleteEntry(key) {
      console.log("Delete Entry");
      if (this.entries[key].hasOwnProperty("time")) {
        chrome.alarms.clear(key); // clearing alarm if it has time
      }
      Vue.delete(this.entries, key);
      actions
        .delete({ date: this.dateStamp, key })
        .then((result) => {
          // console.log(result);
        })
        .catch((e) => console.error(e));
    },

    //===============
    // END CRUD FUNCTIONS
    //===============
  },
  computed: {
    dateStamp() {
      return this.listDate.toLocaleDateString("en-US").replaceAll("/", "-");
    },
    dayNumber() {
      return this.listDate.getDate();
    },
    todayDate() {
      if (
        this.listDate.toLocaleDateString("en-US") ===
        new Date().toLocaleDateString("en-US")
      ) {
        return {
          background: "rgba(5,80,123,0.992)",
          borderRadius: "75px",
        };
      }
    },
    addClasses() {
      // classnames is a list
      if (this.isOver && this.classNames) {
        let classList = this.classNames.slice();
        classList.push("over");
        return classList;
      }
      return this.classNames;
    },
  },
};
</script>

<style scoped lang="scss">
@import "./style.scss";
</style>

// src/components/EntryList/EntryList.jsx
import { useEffect, useState } from 'preact/hooks';
import shortid from 'shortid';
import { actions, entryMoved } from '../../utils/index';
import Entry from '../Entry/Entry';

import styles from './EntryList.module.scss';

function EntryList({ date, dateStamp }) {
  const [entries, setEntries] = useState([]);
  const [isOver, setIsOver] = useState(false);
  //   const [entryMoved, setEntryMoved] = useState(false);
  const initEntry = () => {
    console.info('initEntry');
    // Add to entries state and to chrome storage
    const key = shortid.generate();
    let newEntry = {
      key,
      text: '',
      color: 'blue',
      active: false,
      new: true,
    };

    setEntries((prevEntries) => [...prevEntries, newEntry]);
  };

  const createEntry = (entry) => {
    const index = entries.findIndex((e) => e.key === entry.key);
    setEntries((prevEntries) => {
      const updatedEntries = prevEntries.slice();
      if (index >= 0) {
        delete updatedEntries[index].new;
      } else {
        updatedEntries.push(entry);
      }
      return updatedEntries;
    });
    actions
      .create({ date: dateStamp, entry, key: entry.key })
      .then((result) => {})
      .catch((e) => console.error(e));
  };
  const readEntries = () => {
    console.info('readEntries');
    actions
      .read({ date: dateStamp })
      .then((result) => {
        setEntries(result);
      })
      .catch((e) => console.error(e));
  };
  const updateEntry = (key, updatedEntry) => {
    console.info('updateEntry');

    // we should update the entries?
    const index = entries.findIndex((e) => e.key === key);
    setEntries((prevEntries) => {
      const updatedEntries = prevEntries.slice();
      updatedEntries[index] = updatedEntry;
      return updatedEntries;
    });
    // check if entry is any different than before
    // const entry = entries[index];
    actions
      .update({ date: dateStamp, entry: updatedEntry, key })
      .then((result) => {})
      .catch((e) => console.error(e));
  };
  const deleteEntry = (key) => {
    console.info('Delete Entry');
    const index = entries.findIndex((e) => e.key === key);
    if (entries[index].hasOwnProperty('time')) {
      chrome.alarms.clear(key); // clearing alarm if it has time
    }
    setEntries((prevEntries) => {
      const updatedEntries = prevEntries.slice();
      updatedEntries.splice(index, 1);
      return updatedEntries;
    });
    actions
      .delete({ date: dateStamp, key })
      .then((result) => {})
      .catch((e) => console.error(e));
  };
  const entryDragEnd = (event, key) => {
    console.log('entry drag end');
    if (entryMoved.value) {
      entryMoved.value = false;
      deleteEntry(key);
    }
  };
  const entryDragStart = (event, entry, originalDate) => {
    event.dataTransfer.setData('application/json', JSON.stringify(entry));
    event.dataTransfer.setData('date', originalDate);
    event.dataTransfer.setData('key', entry.key);
    event.dataTransfer.effectAllowed = 'move';
  };
  const onDrop = (event) => {
    setIsOver(false);
    const originalDate = event.dataTransfer.getData('date');
    if (originalDate === dateStamp) return;
    entryMoved.value = true;
    const entry = JSON.parse(event.dataTransfer.getData('application/json'));
    createEntry(entry);
  };
  const dragOver = (event) => {
    setIsOver(true);
    event.preventDefault();
    event.stopPropagation();
  };
  const dragLeave = (event) => {
    setIsOver(false);
  };
  useEffect(() => {
    readEntries();
  }, [date]);
  return (
    <div
      className={`${styles.details} ${isOver ? styles.over : ''}`}
      onDragOver={dragOver}
      onDragLeave={dragLeave}
      onDrop={onDrop}
    >
      <div
        // v-if="dateTitle"
        // :style="todayDate"
        className={styles.dateTitle}
      >
        {date.getDate()}
      </div>

      <ul className={styles.entryList}>
        {entries.length > 0
          ? entries.map((entry) => (
              <Entry
                entryDragEnd={entryDragEnd}
                entryDragStart={entryDragStart}
                createEntry={createEntry}
                updateEntry={updateEntry}
                deleteEntry={deleteEntry}
                dateStamp={dateStamp}
                entry={entry}
              />
            ))
          : ''}
      </ul>
      <ul className={styles.entryList}></ul>

      <button
        onClick={initEntry}
        // :value="dateStamp"
        className={styles.addButton}
      >
        +
      </button>
    </div>
  );
}

export default EntryList;
