// src/js/app/components/Calendar.vue
<template>
  <div id="vuemain">
    <div id="view">
      <button @click="changeView('daily')" type="button" class="view-btn">
        Daily
      </button>
      <button @click="changeView('week')" type="button" class="view-btn">
        Week
      </button>
      <button @click="changeView('month')" type="button" class="view-btn">
        Month
      </button>
    </div>
    <div v-if="view === 'daily'">
      <section>
        <Day />
      </section>
    </div>
    <div v-if="view === 'week'">
      <section>
        <Week />
      </section>
    </div>
    <div v-if="view === 'month'">
      <section>
        <Month />
      </section>
    </div>
  </div>
</template>


<script>
import Day from "./Day";
import Week from "./Week";
import Month from "./Month";

export default {
  components: {
    Day,
    Week,
    Month,
  },
  data() {
    return {
      view: "",
    };
  },

  created() {
    chrome.storage.sync.get(["view"], (result) => {
      this.view = result.view;
    });
  },

  methods: {
    changeView(type) {
      chrome.storage.sync.set({ view: type }, () => {
        this.view = type;
      });
    },
  },
};
</script>

<style lang="scss" scoped>
</style>

// src/components/Calendar/Calendar.jsx
import { useState, useEffect } from 'preact/hooks';
import Day from '../Day/Day';
import Month from '../Month/Month';
import Week from '../Week/Week';

import styles from './Calendar.module.scss';

function Calendar() {
  const [component, setComponent] = useState(null);
  useEffect(() => {
    setComponent(<Day />);
  }, []);

  const changeView = (type) => {
    switch (type) {
      case 'day':
        setComponent(<Day />);
        break;
      case 'week':
        setComponent(<Week />);
        break;
      case 'month':
        setComponent(<Month />);
        break;
    }
  };
  return (
    <div id="vuemain">
      <div id={styles.view}>
        <button
          onClick={() => changeView('day')}
          type="button"
          className={styles.view_btn}
        >
          Daily
        </button>
        <button
          onClick={() => changeView('week')}
          type="button"
          className={styles.view_btn}
        >
          Week
        </button>
        <button
          onClick={() => changeView('month')}
          type="button"
          className={styles.view_btn}
        >
          Month
        </button>
      </div>
      <div>
        <section>{component}</section>
      </div>
    </div>
  );
}

export default Calendar;
