// src/js/app/App.vue
<template>
  <div>
    <Navbar />
    <main ref="main">
      <Clock />
      <Calendar />
    </main>
  </div>
</template>

<script>
import Navbar from "./components/Navbar.vue";
import Clock from "./components/Clock.vue";
import Calendar from "./components/Calendar.vue";

export default {
  components: {
    Navbar,
    Clock,
    Calendar,
  },

  created() {
    // This is where I should check if I have it set as default new tab or not
    this.setBackground();
  },

  methods: {
    //   Work on the background transition to load on page
    setBackground() {
      chrome.storage.sync.get(["background", "userSettings"], (result) => {
        // Background Photo
        let page = document.getElementsByTagName("html");
        page[0].style.background = `rgba(0,0,0,0.9) url(${
          result.background.url + `&w=${window.innerWidth}`
        }) no-repeat fixed`;
        //
        this.$refs.main.style.display = result.userSettings.pmode
          ? "none"
          : "block";
      });
    },

    checkLogin() {},
  },
};
</script>

<style lang="scss" scoped>
main {
  margin: 1rem auto;
  justify-content: center;
  width: 100%;
  animation-name: fadeIn;
  animation-duration: 0.4s;
  animation-fill-mode: forwards;
}
</style>

// src/app/App.jsx
import { useEffect, useRef } from 'preact/hooks';

import Navbar from '../components/Navbar/Navbar.jsx';
import Clock from '../components/Clock/Clock.jsx';
import Calendar from '../components/Calendar/Calendar.jsx';
import { userSettings, backgroundInfo } from '../utils/index.jsx';

import './styles.scss';

function App() {
  const backgroundRef = useRef(null);

  const mountBackground = () => {
    if (!backgroundInfo.value.url) return;
    const page = document.getElementsByTagName("html");
    const image = backgroundInfo.value.url;
    page[0].style.background = `rgba(0,0,0,0.9) url(${image + `&w=${window.innerWidth}`
      }) no-repeat fixed`;
    backgroundRef.current.style.display = userSettings.value.pmode
      ? "none"
      : "block";
  }

  useEffect(() => {
    mountBackground();
  }, [backgroundInfo.value])
  return (
    <div>
      <Navbar />
      <main ref={backgroundRef}>
        <Clock />
        <Calendar />
      </main>
    </div>
  );
}

export default App;
