// src/app/App.jsx
import { useEffect, useRef } from 'preact/hooks';

import Navbar from '../components/Navbar/Navbar.jsx';
import Clock from '../components/Clock/Clock.jsx';
import Calendar from '../components/Calendar/Calendar.jsx';
import { userSettings, actions } from '../utils/index.jsx';
import './styles.scss';

function App() {
  const backgroundRef = useRef(null);

  const mountBackground = () => {
    console.log('mountBackground')
    actions.getBackground().then((background) => {
      if (!background) return;
      const page = document.getElementsByTagName("html");
      const image = background.url;
      page[0].style.background = `rgba(0,0,0,0.9) url(${image + `&w=${window.innerWidth}`
        }) no-repeat fixed`;
      backgroundRef.current.style.display = userSettings.value.pmode
        ? "none"
        : "block";
    })
  }

  useEffect(() => {
    mountBackground();
  }, [])
  return (
    <div>
      <Navbar />
      <main ref={backgroundRef}>
        <Clock />
        <Calendar />
      </main>
    </div>
  );
}

export default App;

// extension/src/js/app/App.vue
<template>
  <div>
    <Navbar />
    <main ref="main">
      <Clock />
      <Calendar />
    </main>
  </div>
</template>

<script>
import Navbar from "./components/Navbar.vue";
import Clock from "./components/Clock.vue";
import Calendar from "./components/Calendar.vue";

export default {
  components: {
    Navbar,
    Clock,
    Calendar,
  },
  beforeCreate() {
    // console.log("app started");
  },
  created() {
    window.addEventListener("resize", this.setBackground);
    this.setBackground();
  },
  destroyed() {
    window.removeEventListener("resize", this.setBackground);
  },
  methods: {
    //   Work on the background transition to load on page
    setBackground() {
      let page = document.getElementsByTagName("html");
      chrome.storage.sync.get(["background", "userSettings"], (result) => {
        chrome.storage.sync.get("image", (syncRes) => {
          if (Object.keys(syncRes).length > 0) {
            let image = syncRes.image;
            page[0].style.background = `url(${image})`;
          } else {
            let image = result.background.url;
            page[0].style.background = `rgba(0,0,0,0.9) url(${
              image + `&w=${window.innerWidth}`
            }) no-repeat fixed`;
          }
        });
        this.$refs.main.style.display = result.userSettings.pmode
          ? "none"
          : "block";
      });
    },
  },
};
</script>

<style lang="scss" scoped>
main {
  margin: 1rem auto;
  justify-content: center;
  width: 100%;
}
</style>
