// src/components/Calendar/Calendar.jsx
import Day from '../Day/Day';
import Month from '../Month/Month';
import Week from '../Week/Week';
import { userSettings } from '../../utils';

import styles from './Calendar.module.scss';

function Calendar() {
  const changeView = (type) => {
    switch (type) {
      case 'day':
        userSettings.value = { ...userSettings.value, view: type };
        break;
      case 'week':
        userSettings.value = { ...userSettings.value, view: type };
        break;
      case 'month':
        userSettings.value = { ...userSettings.value, view: type };
        break;
    }
  };
  return (
    <div id="vuemain">
      <div id={styles.view}>
        <button
          onClick={() => changeView('day')}
          type="button"
          className={styles.view_btn}
        >
          Daily
        </button>
        <button
          onClick={() => changeView('week')}
          type="button"
          className={styles.view_btn}
        >
          Week
        </button>
        <button
          onClick={() => changeView('month')}
          type="button"
          className={styles.view_btn}
        >
          Month
        </button>
      </div>
      <div>
        <section>
          {userSettings.value.view === 'day' && <Day />}
          {userSettings.value.view === 'week' && <Week />}
          {userSettings.value.view === 'month' && <Month />}
        </section>
      </div>
    </div>
  );
}

export default Calendar;

// extension/src/js/app/components/Calendar.vue
<template>
  <div id="vuemain">
    <div id="view">
      <button @click="changeView('daily')" type="button" class="view-btn">
        Daily
      </button>
      <button @click="changeView('week')" type="button" class="view-btn">
        Week
      </button>
      <button @click="changeView('month')" type="button" class="view-btn">
        Month
      </button>
    </div>
    <div v-if="userSettings.view === 'daily'">
      <section>
        <Day />
      </section>
    </div>
    <div v-if="userSettings.view === 'week'">
      <section>
        <Week />
      </section>
    </div>
    <div v-if="userSettings.view === 'month'">
      <section>
        <Month />
      </section>
    </div>
  </div>
</template>


<script>
import Day from "./Day";
import Week from "./Week";
import Month from "./Month";

export default {
  components: {
    Day,
    Week,
    Month,
  },
  data() {
    return {
      userSettings: {},
     };
  },

  created() {
    chrome.storage.sync.get("userSettings", (result) => {
      let { userSettings } = result;
      this.userSettings = userSettings;
    });
  },

  methods: {
    changeView(type) {
      this.userSettings.view = type;
      let userSettings = this.userSettings;
      chrome.storage.sync.set({ userSettings });
    },
  },
};
</script>

<style lang="scss" scoped>
</style>
