// src/components/Month/Month.jsx
import { useState, useEffect } from 'preact/hooks';
import EntryList from '../EntryList/EntryList';
import styles from './Month.module.scss';
function Month() {
  const [date, setDate] = useState(new Date());
  const [monthTitle, setMonthTitle] = useState('');
  const [weekdays, setWeekdays] = useState([]);
  const [dateList, setDateList] = useState([]);

  const changeMonth = (amount) => {
    let changeDate = new Date(date); // current date:
    changeDate.setMonth(changeDate.getMonth() + amount);
    setDate(changeDate);
  };
  const createWeekdays = () => {
    let startDate = new Date(date);
    // This is how we set it to sunday
    const days = [];
    while (startDate.getDay() !== 0) {
      // while startDate.getDay is not equal to 0, continue to set date
      startDate.setDate(startDate.getDate() - 1);
    }
    for (let i = 0; i < 7; i++) {
      let dayDate = new Date(startDate).toLocaleDateString(undefined, {
        weekday: 'long',
      });
      days.push(dayDate);
      startDate.setDate(startDate.getDate() + 1);
    }
    setWeekdays(days);
  };

  const createDateList = () => {
    let dates = [];
    let startDate = new Date(date);
    let currentMonth = startDate.getMonth(); // what month is it
    startDate.setDate(1); // set it to day 1 of month

    // This is how we set it to sunday
    while (startDate.getDay() !== 0) {
      // while startDate.getDay is not equal to 0, continue to set date
      startDate.setDate(startDate.getDate() - 1);
    }

    // I think that this is not working because eventually when we change years, we might be in a different month thing not too sure
    // instead check if its equal to the next month. Easy!
    let nextDate = new Date();
    nextDate.setMonth(currentMonth + 1);
    // if the startDate month is equal to the next month, then exit this loop
    while (startDate.getMonth() !== nextDate.getMonth()) {
      let week = makeWeek();
      dates = [...dates, ...week];
    }

    // Make a week while we are still in the same month
    function makeWeek() {
      let week = [];
      for (let i = 0; i < 7; i++) {
        let dayDate = new Date(startDate);
        week.push(dayDate);
        startDate.setDate(startDate.getDate() + 1);
      }
      return week;
    }
    setDateList(dates);
  };

  useEffect(() => {
    let options = { month: 'long', year: 'numeric' };
    setMonthTitle(date.toLocaleDateString(undefined, options));
    createWeekdays();
    createDateList();
  }, [date]);
  return (
    <div id={styles.month}>
      <div className={styles.nav}>
        <button onClick={() => changeMonth(-1)} className="arrow">
          ←
        </button>
        <div
          className="title"
          style="background: rgba(5, 80, 123, 0.992); border-radius: 75px"
        >
          {monthTitle}
        </div>
        <button onClick={() => changeMonth(1)} className="arrow">
          →
        </button>
      </div>
      <div className={styles.weekdayNames}>
        {weekdays.length > 0
          ? weekdays.map((day) => (
              <h2 style="padding: 0px 0px 0.5rem; text-align: center">{day}</h2>
            ))
          : ''}
      </div>
      <div className={styles.monthDays}>
        {dateList.length > 0
          ? dateList.map(() => (
              <div className={styles.monthDay}>
                <EntryList />
              </div>
            ))
          : ''}
        {/* <EntryList
            v-for="(date, index) in dateList"
            :ref="`${index}`"
            :key="index"
            :id="index"
            :listDate="date"
            :dateTitle="true"
            :classNames="['monthDay']"
          /> */}
      </div>
    </div>
  );
}
export default Month;

// extension/src/js/app/components/month.vue
<template>
  <div id="month">
    <div class="nav">
      <button @click="changeMonth(-1)" class="arrow">←</button>
      <div
        class="title"
        style="background: rgba(5, 80, 123, 0.992); border-radius: 75px"
      >
        {{ monthTitle }}
      </div>
      <button @click="changeMonth(1)" class="arrow">→</button>
    </div>
    <div class="weekdayNames">
      <h2 style="padding: 0px 0px 0.5rem; text-align: center">Sunday</h2>
      <h2 style="padding: 0px 0px 0.5rem; text-align: center">Monday</h2>
      <h2 style="padding: 0px 0px 0.5rem; text-align: center">Tuesday</h2>
      <h2 style="padding: 0px 0px 0.5rem; text-align: center">Wednesday</h2>
      <h2 style="padding: 0px 0px 0.5rem; text-align: center">Thursday</h2>
      <h2 style="padding: 0px 0px 0.5rem; text-align: center">Friday</h2>
      <h2 style="padding: 0px 0px 0.5rem; text-align: center">Saturday</h2>
    </div>
    <div class="monthDays">
      <EntryList
        v-for="(date, index) in dateList"
        :key="index"
        :listDate="date"
        :dateTitle="true"
        :classNames="['monthDay']"
      />
    </div>
  </div>
</template>

<style lang="scss" scoped>
#month {
  flex-direction: column;
  justify-content: center;
  .weekdayNames {
    display: grid;
    grid-template-columns: repeat(7, minmax(50px, 1fr));
    width: 98%;
    margin: 0 auto;
  }
  .monthDays {
    display: grid;
    grid-template-columns: repeat(7, minmax(50px, 1fr));
    width: 98%;
    margin: 0 auto;

    .monthDay {
      text-shadow: 0 0 25px rgba(0, 0, 0, 0.9);
      height: 13rem;
      padding: 0.75rem;
      // border: 0.5px solid $border-color;
      border: 0.5px solid rgba(32, 32, 32, 0.555);
      float: left;
      // background: $day-background;
      background: rgba(0, 0, 0, 0.15);
      transition: background 0.5s;
    }
  }
}
</style>
<script>
import EntryList from "./EntryList/index.vue";
export default {
  components: {
    EntryList,
  },

  data() {
    return {
      date: new Date(),
    };
  },

  created() {},

  methods: {
    changeMonth(amount) {
      let changeDate = new Date(this.date); // current date:
      changeDate.setMonth(this.date.getMonth() + amount);
      this.date = changeDate;
    },
  },
  computed: {
    monthTitle() {
      let options = { month: "long", year: "numeric" };
      let date = new Date(this.date);
      return date.toLocaleDateString(undefined, options);
    },

    // what is date list? -> Used for making Entry Lists
    dateList() {
      let dates = [];
      let startDate = new Date(this.date);
      let currentMonth = startDate.getMonth(); // what month is it
      startDate.setDate(1); // set it to day 1 of month

      // This is how we set it to sunday
      while (startDate.getDay() !== 0) {
        // while startDate.getDay is not equal to 0, continue to set date
        startDate.setDate(startDate.getDate() - 1);
      }

      // I think that this is not working because eventually when we change years, we might be in a different month thing not too sure
      // instead check if its equal to the next month. Easy!
      let nextDate = new Date();
      nextDate.setMonth(currentMonth + 1);
      // if the startDate month is equal to the next month, then exit this loop
      while (startDate.getMonth() !== nextDate.getMonth()) {
        let week = makeWeek();
        dates = [...dates, ...week];
      }

      // Make a week while we are still in the same month
      function makeWeek() {
        let week = [];
        for (let i = 0; i < 7; i++) {
          let dayDate = new Date(startDate);
          week.push(dayDate);
          startDate.setDate(startDate.getDate() + 1);
        }
        return week;
      }
      return dates;
    },
  },
};
</script>
