// src/components/Navbar/Navbar.jsx
import styles from './Navbar.module.scss';
import { backgroundInfo, userSettings } from '../../utils';

function Navbar() {

  const togglePhotoMode = () => {
    userSettings.value.pmode = !userSettings.value.pmode;
  }

  return (
    <ul id={styles.nav}>
      <li id="app_info_box">
        <div id={styles.app_info}>
          <div
            id={styles.app_title}
            //   ref="title"
          >
            {/* To bring in the img, we must use "/assets" in order to create a relative path for the compiler to find */}
            <img
              className={styles.app_icon}
              src="/assets/polus_icon.png"
              alt="App icon"
            />
          </div>
          <div id={styles.app_items}>
            <a href="https://mail.google.com/mail/u/0/"> Gmail </a>
            <a href="https://drive.google.com/drive/u/0/"> Drive </a>
            <a
              target="_blank"
              rel="noopener noreferrer"
              href="https://danielchicchon.com/polus"
            >
              Site
            </a>
            <a
              target="_blank"
              rel="noopener noreferrer"
              href="https://docs.google.com/forms/d/e/1FAIpQLSdHcPhbcAWeWFvEFqF6qzmPUD0UtNn9e7pn_eLUukGLudMy1A/viewform"
            >
              Feedback
            </a>
            <a
              id={styles.pmode}
              // @click="photoMode"
              target="_blank"
              rel="noopener noreferrer"
            >
              Photo Mode
            </a>
          </div>
        </div>
      </li>

      <li id="background_info_box" style="float: right">
        <div id={styles.background_info}>
          <span id={styles.background_location}> {backgroundInfo.value.location}</span>
          <span id={styles.background_source}>
            Photo by
            <a
              id={styles.photo_link}
              href={
                backgroundInfo.value.photoLink + '?utm_source=Planner&utm_medium=referral'
              }
              // :href="link"
              target="_blank"
              rel="noopener noreferrer"
            >
              {' '}
              {backgroundInfo.value.author}{' '}
            </a>
            on{' '}
            <a
              id={styles.site_link}
              target="_blank"
              rel="noopener noreferrer"
              href="https://unsplash.com/?utm_source=Polus&utm_medium=referral"
            >
              Unsplash
            </a>
            <a id={styles.download} rel="nofollow" target="_blank" download>
              &#8681;
            </a>
          </span>
        </div>
      </li>
    </ul>
  );
}

export default Navbar;

// extension/src/js/app/components/Navbar.vue
<template>
  <ul id="nav">
    <li id="app-info-box">
      <div id="app-info">
        <div id="app-title" ref="title">
          <!-- To bring in the img, we must use "/assets" in order to create a relative path for the compiler to find -->
          <img class="app-icon" src="/assets/polus_icon.png" alt="App icon" />
        </div>
        <div id="app-items" ref="items">
          <a href="https://mail.google.com/mail/u/0/">
            Gmail
          </a>
          <a href="https://drive.google.com/drive/u/0/">
            Drive
          </a>
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://danielchicchon.io/polus"
            >Site</a
          >
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://docs.google.com/forms/d/e/1FAIpQLSdHcPhbcAWeWFvEFqF6qzmPUD0UtNn9e7pn_eLUukGLudMy1A/viewform"
          >
            Feedback</a
          >
          <a
            id="pmode"
            @click="photoMode"
            target="_blank"
            rel="noopener noreferrer"
            >Photo Mode</a
          >
        </div>
      </div>
    </li>

    <li id="background-info-box" style="float: right">
      <div id="background-info">
        <span id="background-location"> {{ location }}</span>
        <span id="background-source"
          >Photo by
          <a
            id="photo-link"
            :href="link"
            target="_blank"
            rel="noopener noreferrer"
            >{{ author }}</a
          >
          on
          <a
            id="site-link"
            target="_blank"
            rel="noopener noreferrer"
            href="https://unsplash.com/?utm_source=Planner&utm_medium=referral"
            >Unsplash
          </a>
          <a id="download" rel="nofollow" target="_blank" download>&#8681;</a>
        </span>
      </div>
    </li>
  </ul>
</template>
<script>
export default {
  data() {
    return {
      location: "",
      download: "",
      author: "",
      link: "",
      pmode: false,
    };
  },
  created() {
    chrome.storage.sync.get(["background", "userSettings"], (result) => {
      this.pmode = result.userSettings.pmode;
      this.location = result.background.location
        ? result.background.location
        : "Unknown";
      this.download = result.background.downloadLink;
      this.author = result.background.author;
      this.link =
        result.background.photoLink + "?utm_source=Planner&utm_medium=referral";
    });
  },

  methods: {
    photoMode() {
      this.pmode = !this.pmode;
      chrome.storage.sync.get("userSettings", (result) => {
        let { userSettings } = result;
        userSettings.pmode = this.pmode;
        chrome.storage.sync.set({ userSettings });
      });
      let mainView = document.getElementsByTagName("main");
      mainView[0].style.display = this.pmode ? "none" : "block";
    },
  },
};
</script>
<style lang="scss" scoped>
#nav {
  list-style-type: none;
  top: 0;
  height: 3rem;
  width: 100%;
  margin: 0;
  padding: 0;
  li {
    float: left;
    display: block;
    a {
      text-decoration: none;
    
    }
  }
}

#app-info {
  display: grid;
  font-size: 1.5rem;
  height: 45px;
  &:hover {
    #app-title {
      display: none;
    }
    #app-items {
      display: inline-block;
    }
  }
  // Default Display
  #app-title {
    padding: 10px;
    grid-column: 1;
    grid-row: 1;
    display: inline-block;
    animation-name: fadeIn;
    animation-duration: 0.75s;
    animation-fill-mode: forwards;
    .app-icon {
      width: 35px;
      height: 35px;
    }
    .app-sub {
      display: inline-block;
      font-weight: 200;
      letter-spacing: 0.1rem;
      text-shadow: 0 0 15px rgba(0, 0, 0, 1);
      transform: translateY(-25%);
    }
  }

  #app-items {
    display: none;
    background: rgba(15, 15, 15, 0.6);
    border-bottom-right-radius: 8px;
    grid-column: 1;
    grid-row: 1;
    animation-name: fadeIn;
    animation-duration: 0.75s;
    animation-fill-mode: forwards;

    // eventually remove this please
    a {
      transition: background 0.25s;
      font-size: 15px;
      padding: 10px;
      cursor: pointer;
      display: inline-block;
      &:hover {
        background-color: rgba($color: white, $alpha: 0.1);
      }
    }
  }
}

#background-info {
  // padding: 1rem;
  display: grid;
  text-align: center;
  font-size: 1rem;
  background-blend-mode: screen;
  // background: none;
  &:hover {
    #background-location {
      display: none;
    }
    #background-source {
      display: inline-block;
    }
  }
  // Default Display

  #background-location {
    grid-column: 1;
    grid-row: 1;
    padding: 0.75rem;
    display: inline-block;
    animation-name: fadeIn;
    animation-duration: 0.75s;
    animation-fill-mode: forwards;
  }
  #background-source {
    display: none;
    padding: 0.5rem;
    font-size: 1rem;
    border-bottom-left-radius: 8px;
    background: rgba(15, 15, 15, 0.6);
    grid-column: 1;
    grid-row: 1;
    // opacity: 0;
    animation-name: fadeIn;
    animation-duration: 0.75s;
    animation-fill-mode: forwards;
    a {
      text-decoration: none;
    }
    a:hover {
      text-decoration: underline;
    }
    #download {
      margin-left: 0.5rem;
      color: white;
      cursor: pointer;
    }
  }

  #background-link {
    position: relative;
    text-decoration: none;
    color: white;
  }
}

.google-dropdown-btn {
  cursor: none;
  background: none;
}
.google-dropdown {
  position: relative;
  &:hover {
    .google-dropdown-content {
      display: block;
    }
  }
}
.google-dropdown-content {
  display: none;
  position: absolute;
  background: rgba(15, 15, 15, 0.6);
}
</style>
